version: 2
jobs:
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Package
          command: npm run build
      - run:
          name: Deploy
          command: bash ./scripts/deploy.sh my.awesome.website 

workflows:
:x
  build_and_deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master


